### ISSUE TITLE
Wrong license badge?

### ISSUE THREAD

**Issue by gmorenz** [llogiq/nsa#3]
License badge claims to be MIT, License file and Cargo.toml say MPL2.

**Comment by Manishearth** [comment]
Sounds like something the NSA would do.

**Comment by Manishearth** [comment]
The initial license was MPL.

Might be better triple licensed as MPL/MIT/Apache v2? This enables it to be seamlessly upstreamed to both Rust and Clippy/Servo.

Then again, IIRC MPL is MIT compat so it should be okay? No idea how this works.

**Comment by llogiq** [comment]
This is a mistake on my part. I'll fix it once I find the time.
